# Docker file for building Overte Server
# Example build: docker build -t juliangro/overte-server-build:0.1 -f tools/ci-scripts/docker_package/Dockerfile_build .
FROM debian:bullseye
LABEL maintainer="Julian Groß (julian.gro@overte.org)"
LABEL description="Development image for Overte Domain server and assignment clients."

# Don't use any frontend when installalling packages during the creation of this container
ARG DEBIAN_FRONTEND=noninteractive

RUN echo UTC >/etc/timezone
# Installing via dependency causes interactive hang:
RUN apt-get -y install tzdata

# Install Overte domain-server and assignment-client build dependencies
RUN apt-get update && apt-get -y install curl ninja-build git cmake g++ libssl-dev libqt5websockets5-dev qtscript5-dev qtdeclarative5-dev qtmultimedia5-dev

# Install tools for creating the server image
RUN apt-get -y install docker.io xz-utils

# Install tools needed for our Github Actions Workflow
Run apt-get -y install python3-boto3 python3-github zip
