name: "Gather debug information"
description: "Prints information potentially useful when troubleshooting a failing job."
runs:
    using: "composite"
    steps:
    - name: Output disk usage
      if: ${{ always() }}
      shell: bash
      continue-on-error: true
      run: df -h

    - name: Output Windows installer logs
      if: startsWith(matrix.os, 'Windows')
      shell: bash
      working-directory: build
      run: cat ./_CPack_Packages/win64/NSIS/NSISOutput.log || echo "No NSIS log found. Continuing…"

    - name: Output CodeChecker JSON compilation database
      if: matrix.id == 'codechecker'
      shell: bash
      continue-on-error: true
      run: cat ${{ env.GITHUB_WORKSPACE }}/codechecker_codechecker_compilation_database.json
