# Copyright 2022 Overte e.V.
# SPDX-License-Identifier: MIT

# Docker file for building Overte Server
# Example build: docker build -t overte/overte-server-build:0.1.1-ubuntu-18.04 -f Dockerfile_build_ubuntu-18.04 .
FROM ubuntu:18.04
LABEL maintainer="Julian Groß (julian.gro@overte.org)"
LABEL description="Development image for Overte Domain server and assignment clients."

# Don't use any frontend when installalling packages during the creation of this container
ARG DEBIAN_FRONTEND=noninteractive

RUN echo UTC >/etc/timezone
# Installing via dependency causes interactive hang:
RUN apt-get update && apt-get -y install tzdata

# Install Overte domain-server and assignment-client build dependencies
RUN apt-get -y install curl ninja-build git g++ libssl-dev python3-distutils python3-distro mesa-common-dev libgl1-mesa-dev libharfbuzz-dev libdouble-conversion1

# Install tools for package creation
RUN apt-get -y install sudo chrpath binutils dh-make

# Install locales package
RUN apt-get -y install locales
# Uncomment en_US.UTF-8 for inclusion in generation
RUN sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
# Generate locale
RUN locale-gen

# Export env vars
RUN echo "export LC_ALL=en_US.UTF-8" >> ~/.bashrc
RUN echo "export LANG=en_US.UTF-8" >> ~/.bashrc
RUN echo "export LANGUAGE=en_US.UTF-8" >> ~/.bashrc

# Install tools for creating the server image
RUN apt-get -y install docker.io xz-utils

# Install tools needed for our Github Actions Workflow
RUN apt-get -y install python3-boto3 python3-github zip

# Install newer CMake
RUN curl -O -L https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-linux-x86_64.tar.gz
RUN tar -xf cmake-3.24.0-linux-x86_64.tar.gz
ENV PATH="/cmake-3.24.0-linux-x86_64/bin:$PATH"
