macro(TARGET_AFF)
    if(OVERTE_USE_SYSTEM_LIBS)
        find_path(AFF_INCLUDE_DIRS "artery-font/artery-font.h")
        target_include_directories(${TARGET_NAME} SYSTEM PRIVATE ${AFF_INCLUDE_DIRS})
    else()
        find_package(artery-font-format REQUIRED)
        target_link_libraries(${TARGET_NAME} artery-font-format::artery-font-format)
    endif()
endmacro()
