//
// Created by ksuprynowicz on 14.11.24.
//

#ifndef OVERTE_SCRIPTENGINEDEBUGFLAGS_H
#define OVERTE_SCRIPTENGINEDEBUGFLAGS_H

#define OVERTE_SCRIPT_USE_AFTER_DELETE_GUARD

#endif  //OVERTE_SCRIPTENGINEDEBUGFLAGS_H
