# syntax=docker/dockerfile:1.4

# Copyright 2022-2026 Overte e.V.
# SPDX-License-Identifier: Apache-2.0

# Docker file for building Overte
# Example build: docker build --no-cache --progress=plain -t overte/overte-full-build:2026-06-21-ubuntu-22.04-amd64 -f Dockerfile_build_ubuntu-22.04 .
FROM ubuntu:22.04
LABEL maintainer="Julian Groß (julian.gro@overte.org)"
LABEL description="Development image for full Overte builds"

# Use bash instead of sh
SHELL ["/bin/bash", "-c"]
# Don't use any frontend when installing packages during the creation of this container
ARG DEBIAN_FRONTEND=noninteractive


#
# Install build dependencies
#
RUN <<EOF
echo UTC >/etc/timezone
# Installing via dependency causes interactive hang:
apt-get update && apt-get -y install tzdata

# Install CMake from Kitware
apt-get -y install ca-certificates gpg wget
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
apt-get update
rm /usr/share/keyrings/kitware-archive-keyring.gpg && apt-get -y install kitware-archive-keyring
apt-get -y install cmake

# Install Overte domain-server and assignment-client build dependencies
cat << PACKAGES > packages.txt
curl
ninja-build
git
g++
libssl-dev
libqt5websockets5-dev
qtdeclarative5-dev
qtmultimedia5-dev
python3-distutils
python3-distro
mesa-common-dev
libgl1-mesa-dev
libsystemd-dev
python3-packaging
# Needed for tools target
libqt5webchannel5-dev
qtwebengine5-dev
libqt5xmlpatterns5-dev
# Needed for interface target
libqt5svg5-dev
qttools5-dev
vulkan-validationlayers
libvulkan-dev
libvulkan1
libqt5x11extras5-dev
qtbase5-private-dev
libxcb-glx0-dev
libqt5multimedia5-plugins
qt5-image-formats-plugins  # Runtime dependency required for WebP texture support.
fcitx5-frontend-qt5  # Runtime dependency for IME support.
npm  # For Interface's JavaScript console completion and building server-console.
libpulse-dev  # Qt5 source Conan package cannot find it's own Pulseaudio
libasound2-dev  # Qt5 source Conan package cannot find it's own ALSA
python3-html5lib  # Qt5 source Conan package cannot install html5lib itself yet. (Required by Qt WebEngine.)
# Tools for package creation
sudo
chrpath
binutils
dh-make
# Tools needed for our Github Actions Workflow
python3-boto3
python3-github
zip
jq
# Used by GitHub Actions @action/cache. Without this, debug builds take 4 minutes instead of 14 seconds to compress for the cache.
zstd
PACKAGES

apt-get -y install $(grep -o '^[^#]*' packages.txt)  # Install packages while ignoring comments.

# Install Conan
apt-get -y install wget
if [ $(uname -m) = "x86_64" ]; then
    wget -O conan.deb https://github.com/conan-io/conan/releases/download/2.25.2/conan-2.25.2-amd64.deb
elif [ $(uname -m) = "aarch64" ]; then
    wget -O conan.deb https://github.com/conan-io/conan/releases/download/2.25.2/conan-2.25.2-arm64.deb
else
    echo "Unsupported architecture: $(uname -m)"
    exit 1
fi
apt-get -y install ./conan.deb
rm conan.deb
EOF


#
# Setup Conan
#
# Set CONAN_HOME, so we can read it in our GitHub Actions cache step.
# This needs to be set to a location that is unlikely to exist on the end-user's system to work around permission issues
# with OpenXR-loader. See https://github.com/overte-org/overte/issues/2117
ENV CONAN_HOME=/zgofepbi/.conan2
RUN <<EOF
conan remote add overte https://artifactory.overte.org/artifactory/api/conan/overte
# Use our mirror of Conan Center to avoid rate limiting.
conan remote update conancenter --url https://artifactory.overte.org/artifactory/api/conan/conan-center

conan profile detect

cat >> ${CONAN_HOME}/profiles/default <<EOFcat
[conf]
# Allow Conan to install system packages.
tools.system.package_manager:mode=install
EOFcat

# Try downloading source files from our source backup server, to avoid hammering third party servers. Fall back to downloading source files from conandata.yml.
echo "core.sources:download_urls=['https://artifactory.overte.org/artifactory/build-dependencies-backup/', 'origin']" >> ${CONAN_HOME}/global.conf
echo "core.sources:upload_url=https://artifactory.overte.org/artifactory/build-dependencies-backup/" >> ${CONAN_HOME}/global.conf
EOF

# Credentials for uploading backups of dependency sources.
# source-credentials.json is a jinja template, so os.getenv() happens at runtime.
COPY <<EOF /root/.conan2/source_credentials.json
{% set TOKEN = os.getenv('CONAN_BUILD_DEPENDENCIES_BACKUP_UPLOAD_TOKEN') %}
{
  "credentials": [
    {% if TOKEN %}
    {
    "url": "https://artifactory.overte.org/artifactory/build-dependencies-backup/",
    "token": "{{TOKEN}}"
    }
    {% endif %}
  ]
}
EOF

#
# CodeChecker
#
# Install CodeChecker and its dependencies
RUN <<EOF
# We only run CodeChecker on amd64.
if [ $(uname -m) = "x86_64" ]; then
    apt update
    apt install -y python3-pip
    # Avoid Ubuntu 22.04's pip version throwing:
    # ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/tmpz4phh0l0/output.json'
    pip3 install --upgrade pip
    # The CodeChecker versions needs to be the same as requested by the CodeChecker-Action.
    pip3 install codechecker==6.28.0

    # Get new CppCheck, instead of Ubuntu's outdated version.
    wget -O cppcheck.tar.gz https://github.com/cppcheck-opensource/cppcheck/archive/refs/tags/2.21.0.tar.gz
    mkdir cppcheck
    tar -xf cppcheck.tar.gz --strip-components=1 -C cppcheck
    rm cppcheck.tar.gz
    cd cppcheck
    cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DHAVE_RULES=ON -DUSE_MATCHCOMPILER=ON
    cmake --build build
    cmake --install build
    cd ..
    rm -rf cppcheck

    # Get new Clang, instead of Ubuntu's outdated version.
    curl -sL http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
    echo 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-22 main' | tee /etc/apt/sources.list.d/llvm.list >/dev/null
    apt update
    apt install -y clang-22 clang-tidy-22
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-22 100
    update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-22 100
else
    echo "We only run CodeChecker on amd64. Skipping for architecture $(uname -m)"
fi
EOF

#
# Platform specific build variables
#
# Work around AppImages not executing in Docker. https://github.com/AppImage/AppImageKit/issues/912#issuecomment-528669441
ENV APPIMAGE_EXTRACT_AND_RUN=1
ENV CONAN_PROFILE="./tools/conan-profiles/linux"

# On macOS the interface target is called "Overte" instead.
ENV APP_TARGET_NAME=interface
