# Copyright 2022 Overte e.V.
# SPDX-License-Identifier: MIT

# Docker file for building Overte Server
# Example build: docker build -t overte/overte-server-build:0.1.2-rockylinux-9 -f Dockerfile_build_rockylinux-9 .
FROM rockylinux:9
LABEL maintainer="Julian Groß (julian.gro@overte.org)"
LABEL description="Development image for Overte Domain server and assignment clients."

# Add required Rocky Linux tools
RUN dnf -y install dnf-utils

# Add "Extra Packages for Enterprise Linux" repository
RUN dnf -y install epel-release
# Add "Code Ready Builder" repository
RUN dnf config-manager --enable crb

# Install Overte domain-server and assignment-client build dependencies
RUN dnf -y install curl ninja-build git cmake gcc-c++ openssl-devel qt5-qtwebsockets-devel qt5-qtscript-devel qt5-qtmultimedia-devel unzip libXext-devel qt5-qtwebchannel-devel qt5-qtwebengine-devel qt5-qtxmlpatterns-devel

# Install additional build tools
RUN dnf -y install zip unzip

# Install tools for package creation
RUN dnf -y install chrpath rpmdevtools

# Install tools needed for our Github Actions Workflow
Run dnf -y install python3-boto3 python3-github
