name: "Prepare Windows environment"
description: "Install tools and dependencies, set environment variables, et cetera."
runs:
    using: "composite"
    steps:
    - name: Set environment variables
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" = "Windows 2022" ]]; then
            echo "CONAN_PROFILE='./tools/conan-profiles/vs-22-release'" >> $GITHUB_ENV
        else
            echo "Not sure which Conan profile to use. Exiting." && exit 1
        fi

        echo "PreferredToolArchitecture=X64" >> $GITHUB_ENV
        echo "APP_NAME=interface" >> $GITHUB_ENV
        # Try to avoid hitting Windows' PATH limit.
        echo "CONAN_HOME=C:\Conan" >> $GITHUB_ENV
        echo "XZ_OPT=-T0" >> $GITHUB_ENV

        echo "OVERTE_QT_SOURCE=source" >> $GITHUB_ENV
        # On macOS the interface target is called "Overte" instead.
        echo "APP_TARGET_NAME=interface" >> $GITHUB_ENV

    - name: Override Windows package versions
      shell: pwsh
      run: |
        choco install nsis --allow-downgrade --version=3.06.1
        choco install cmake --allow-downgrade --version=3.31.6  # Our dependencies don't support CMake 4.0 yet.
        Invoke-WebRequest https://build-deps.overte.org/conan/nsis-overte-plugins/NSIS-hifi-plugins-1.0.zip -OutFile NSIS-hifi-plugins.zip
        Expand-Archive -LiteralPath 'NSIS-hifi-plugins.zip' -DestinationPath 'C:/Program Files (x86)/'

    - name: Install Python modules
      shell: bash
      run: |
        python -m pip install boto3 PyGithub conan html5lib setuptools

    - name: Setup Conan
      shell: bash
      run: |
        echo "Starting with a clean Conan profile…" && rm ${CONAN_HOME}/profiles/default || true  # Don't fail if missing.
        conan profile detect -e
        echo "Printing Conan default profile…" && cat ${CONAN_HOME}/profiles/default

        conan remote add overte https://artifactory.overte.org/artifactory/api/conan/overte -f
        # Use our mirror of Conan Center to avoid rate limiting.
        conan remote update conancenter --url https://artifactory.overte.org/artifactory/api/conan/conan-center

        echo "Starting with a clean Conan global.conf…" && rm ${CONAN_HOME}/global.conf
        # Try downloading source files from conandata.yml first. Fall back to our backup if the upstream source is down.
        echo "core.sources:download_urls=['origin', 'https://artifactory.overte.org/artifactory/build-dependencies-backup/']" >> ${CONAN_HOME}/global.conf
        echo "core.sources:upload_url=https://artifactory.overte.org/artifactory/build-dependencies-backup/" >> ${CONAN_HOME}/global.conf
        # Credentials for uploading backups of dependency sources.
        # source-credentials.json is a jinja template, so os.getenv() happens at runtime.
        cat > ${CONAN_HOME}/source_credentials.json <<EOF
        {% set TOKEN = os.getenv('CONAN_BUILD_DEPENDENCIES_BACKUP_UPLOAD_TOKEN') %}
        {
          "credentials": [
            {
            "url": "https://artifactory.overte.org/artifactory/build-dependencies-backup/",
            "token": "{{TOKEN}}"
            }
          ]
        }
        EOF
        echo "Printing Conan global.conf…" && cat ${CONAN_HOME}/global.conf
        echo "Printing Conan remotes.json…" && cat ${CONAN_HOME}/remotes.json
        echo "Printing Conan source_credentials.json…" && cat ${CONAN_HOME}/source_credentials.json
