#!/bin/sh

if [ "$OVERTE" = "" ]; then
	OVERTE=`realpath ..`
	QT5_LIBS=`realpath ~/vircadia-files/qt/qt5-install/lib`
fi

sudo apt-get install chrpath binutils dh-make

DEB_BUILD_ROOT=temp-make-deb/overte-server_$DEBVERSION
rm -r temp-make-deb
mkdir -p $DEB_BUILD_ROOT

# copy the files over
cp $OVERTE/build/assignment-client/assignment-client $DEB_BUILD_ROOT
cp $OVERTE/build/domain-server/domain-server $DEB_BUILD_ROOT
cp $OVERTE/build/tools/oven/oven $DEB_BUILD_ROOT  # Oven is required for pre-baking assets
cp $OVERTE/build/libraries/*/*.so $DEB_BUILD_ROOT
#cp $OVERTE/build/ice-server/ice-server $DEB_BUILD_ROOT
chrpath -d $DEB_BUILD_ROOT/*
if [ "$OVERTE_USE_SYSTEM_QT" = "" ]; then
	cp $QT5_LIBS/libQt5Network.so.*.*.* $DEB_BUILD_ROOT
	cp $QT5_LIBS/libQt5Core.so.*.*.* $DEB_BUILD_ROOT
	cp $QT5_LIBS/libQt5Widgets.so.*.*.* $DEB_BUILD_ROOT
	cp $QT5_LIBS/libQt5Gui.so.*.*.* $DEB_BUILD_ROOT
	cp $QT5_LIBS/libQt5Script.so.*.*.* $DEB_BUILD_ROOT
	cp $QT5_LIBS/libQt5WebSockets.so.*.*.* $DEB_BUILD_ROOT
	cp $QT5_LIBS/libQt5Qml.so.*.*.* $DEB_BUILD_ROOT
	cp $QT5_LIBS/libQt5ScriptTools.so.*.*.* $DEB_BUILD_ROOT
	chmod +x $DEB_BUILD_ROOT/*.so.*.*.*
fi
strip --strip-all $DEB_BUILD_ROOT/*
cp $OVERTE/pkg-scripts/new-server $DEB_BUILD_ROOT
cp -a $OVERTE/domain-server/resources $DEB_BUILD_ROOT
find $DEB_BUILD_ROOT/resources -name ".gitignore" -delete
find $DEB_BUILD_ROOT/resources -type f -executable -exec sh -c 'chmod -x {}' \;
cp $OVERTE/README.md $DEB_BUILD_ROOT
cp -a $OVERTE/build/assignment-client/plugins $DEB_BUILD_ROOT
strip --strip-all $DEB_BUILD_ROOT/plugins/*.so
strip --strip-all $DEB_BUILD_ROOT/plugins/*/*.so

#begin the debian package construction
cd $DEB_BUILD_ROOT
dh_make -p overte-server_$DEBVERSION -c apache -s --createorig -y

cp $OVERTE/pkg-scripts/overte-assignment-client.service debian
cp $OVERTE/pkg-scripts/overte-assignment-client@.service debian
cp $OVERTE/pkg-scripts/overte-domain-server.service debian
cp $OVERTE/pkg-scripts/overte-domain-server@.service debian
#cp $OVERTE/pkg-scripts/overte-ice-server.service debian
#cp $OVERTE/pkg-scripts/overte-ice-server@.service debian
cp $OVERTE/pkg-scripts/overte-server.target debian
cp $OVERTE/pkg-scripts/overte-server@.target debian

cp $OVERTE/pkg-scripts/server-compat debian/compat
cp $OVERTE/pkg-scripts/server-control debian/control
cp $OVERTE/pkg-scripts/server-prerm debian/prerm
cp $OVERTE/pkg-scripts/server-postinst debian/postinst
cp $OVERTE/pkg-scripts/server-postrm debian/postrm
cp $OVERTE/LICENSE debian/copyright

echo /etc/opt/overte > debian/dirs
echo /var/lib/overte >> debian/dirs

echo README.md > debian/docs

echo assignment-client opt/overte > debian/install
echo domain-server opt/overte >> debian/install
echo oven opt/overte >> debian/install
#echo ice-server opt/overte >> debian/install
echo new-server opt/overte >> debian/install
if [ "$OVERTE_USE_SYSTEM_QT" = "" ]; then
	for so in *.so.*.*.*; do
		echo $so opt/overte/lib >> debian/install
	done
fi
for so in *.so; do
	echo $so opt/overte/lib >> debian/install
done
#for service in *.service; do
#	echo $service opt/overte/systemd >> debian/install
#done
#for target in *.target; do
#	echo $target opt/overte/systemd >> debian/install
#done
find resources -type f -exec sh -c 'echo {} opt/overte/$(dirname "{}") >> debian/install' \;
find plugins -type f -exec sh -c 'echo {} opt/overte/$(dirname "{}") >> debian/install' \;

if [ "$OVERTE_USE_SYSTEM_QT" = "" ]; then
	SOFILES=`ls *.so *.so.*.*.* | grep -Po '^(.+\.so(\.\d+)?)' | sed 's/\./\\\./g' | paste -d'|' -s`
else
	SOFILES=`ls *.so | grep -Po '^(.+\.so(\.\d+)?)' | sed 's/\./\\\./g' | paste -d'|' -s`
fi

DEPENDS=`find * -path debian -prune -o -type f -executable -exec sh -c 'objdump -p {} | grep NEEDED' \; \
	| awk '{print $2}' | sort | uniq | egrep -v "^($SOFILES)$" \
	| xargs -n 1 -I {} sh -c 'dpkg -S {} | head -n 1' | cut -d ':' -f 1 | sort | uniq | paste -d',' -s`

cp $OVERTE/pkg-scripts/server-rules debian/rules
sed "s/{DEPENDS}/$DEPENDS/" $OVERTE/pkg-scripts/server-control > debian/control

dpkg-buildpackage -us -uc

