name: "Prepare macOS environment"
description: "Install tools and dependencies, set environment variables, et cetera."
runs:
    using: "composite"
    steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "CONAN_HOME=$HOME/.conan2" >> $GITHUB_ENV
        echo "XZ_OPT=-T0" >> $GITHUB_ENV

        echo "CONAN_PROFILE='./tools/conan-profiles/macos'" >> $GITHUB_ENV
        echo "APP_TARGET_NAME=Overte" >> $GITHUB_ENV

    - name: Install Python modules
      shell: bash
      run: |
        brew install conan python-setuptools
        python3 -m pip install boto3 PyGithub html5lib --break-system-packages

    - name: Setup Conan
      shell: bash
      run: |
        echo "Starting with a clean Conan profile…" && rm ${CONAN_HOME}/profiles/default || true  # Don't fail if missing.
        conan profile detect -e
        echo "Printing Conan default profile…" && cat ${CONAN_HOME}/profiles/default

        conan remote add overte https://artifactory.overte.org/artifactory/api/conan/overte -f
        # Use our mirror of Conan Center to avoid rate limiting.
        conan remote update conancenter --url https://artifactory.overte.org/artifactory/api/conan/conan-center

        echo "Starting with a clean Conan global.conf…" && rm ${CONAN_HOME}/global.conf
        # Try downloading source files from conandata.yml first. Fall back to our backup if the upstream source is down.
        echo "core.sources:download_urls=['https://artifactory.overte.org/artifactory/build-dependencies-backup/', 'origin']" >> ${CONAN_HOME}/global.conf
        echo "core.sources:upload_url=https://artifactory.overte.org/artifactory/build-dependencies-backup/" >> ${CONAN_HOME}/global.conf
        # Credentials for uploading backups of dependency sources.
        # source-credentials.json is a jinja template, so os.getenv() happens at runtime.
        cat > ${CONAN_HOME}/source_credentials.json <<EOF
        {% set TOKEN = os.getenv('CONAN_BUILD_DEPENDENCIES_BACKUP_UPLOAD_TOKEN') %}
        {
          "credentials": [
            {% if TOKEN %}
            {
            "url": "https://artifactory.overte.org/artifactory/build-dependencies-backup/",
            "token": "{{TOKEN}}"
            }
            {% endif %}
          ]
        }
        EOF
        echo "Printing Conan global.conf…" && cat ${CONAN_HOME}/global.conf
        echo "Printing Conan remotes.json…" && cat ${CONAN_HOME}/remotes.json
        echo "Printing Conan source_credentials.json…" && cat ${CONAN_HOME}/source_credentials.json
