name: "Prepare macOS environment"
description: "Install tools and dependencies, set environment variables, et cetera."
runs:
    using: "composite"
    steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "CONAN_HOME=$HOME/.conan2" >> $GITHUB_ENV
        echo "XZ_OPT=-T0" >> $GITHUB_ENV

        echo "CONAN_PROFILE=default" >> $GITHUB_ENV
        echo "OVERTE_QT_SOURCE=system" >> $GITHUB_ENV
        echo "APP_TARGET_NAME=Overte" >> $GITHUB_ENV
        
        echo "DEVELOPER_DIR=/Applications/Xcode_11.2.app/Contents/Developer" >> $GITHUB_ENV
        # We are using macOS SDK 10.12 to work around a lot of OpenGL issues in newer SDKs.
        # There are crashes on startup, crashes on window resize, etc. on newer macOS SDKs.
        echo "MACOSX_DEPLOYMENT_TARGET=10.12" >> $GITHUB_ENV

    - name: Install Python modules
      shell: bash
      run: |
        python3 -m pip install boto3 PyGithub conan html5lib setuptools
